### ISSUE TITLE
No third shot vaccinations in this country

### ISSUE THREAD

**Issue by skiwlkr** [rbignon/doctoshotgun#290] opened 2021-11-24 14:00 UTC
Hey,
great repo!

I tried to book a third shot with it but always get the error that there is no third shot available in germany/berlin.
Is repo outdated or am I doing something wrong?

Cheers!

**Comment by nicolaus-hee** [comment] 2021-11-24 14:16
Hi, please check:
Duplicate of #82
Addressed in PRs #287, #288, #289

**Comment by skiwlkr** [comment] 2021-11-24 14:27
stupid me.
thanks

**Closed as completed** 2021-11-24 14:27 UTC
